/*
 * VisCadastrarUsuario.java
 *
 * Created on 05/05/2011, 20:50:35
 */
package visao;

import negocio.NegUsuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import persistencia.PerUsuario;
import util.Criptografia;

/**
 * Classe VisCadastrarUsuario da camada de visao
 * 
 * @version 2.3 beta
 * @author Matheus Souza da Silva
 * @since 05/05/2011
 */
public class VisCadastrarUsuario extends javax.swing.JFrame 
{
    /**
    *
    * Método construtor da camada de visao
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 05/05/2011
    */
    public VisCadastrarUsuario() 
    {
        initComponents();
    }//public VisCadastrarUsuario() 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        URL url = this.getClass().getResource("/icones/icone.png");  
	Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
	this.setIconImage(imagemTitulo);  
        
        bgTipo = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlUsuario = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jbCadastrar = new javax.swing.JButton();
        jtUsuario = new javax.swing.JTextField();
        jlSenha = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jlComfirmacao = new javax.swing.JLabel();
        jpfComfirmacao = new javax.swing.JPasswordField();
        jrbAdministrador = new javax.swing.JRadioButton();
        jrbUsuarioComum = new javax.swing.JRadioButton();

        setResizable(true);
        setTitle("Cadastro de Usuário");
        setPreferredSize(new java.awt.Dimension(1000, 395));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Usuário"));

        jlUsuario.setText("Usuário");
        jlUsuario.setBounds(30, 60, 55, 14);
        jLayeredPane1.add(jlUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlTipo.setText("Tipo Usuário");
        jlTipo.setBounds(30, 220, 90, 14);
        jLayeredPane1.add(jlTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/accept.png"))); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.setBounds(30, 270, 150, 25);
        jLayeredPane1.add(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jtUsuario.setBounds(195, 60, 760, 20);
        jLayeredPane1.add(jtUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlSenha.setText("Senha");
        jlSenha.setBounds(30, 110, 50, 14);
        jLayeredPane1.add(jlSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpfSenha.setBounds(195, 100, 760, 20);
        jLayeredPane1.add(jpfSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlComfirmacao.setText("Comfirmação da Senha  ");
        jlComfirmacao.setBounds(30, 160, 170, 14);
        jLayeredPane1.add(jlComfirmacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpfComfirmacao.setBounds(195, 150, 760, 20);
        jLayeredPane1.add(jpfComfirmacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bgTipo.add(jrbAdministrador);
        jrbAdministrador.setSelected(true);
        jrbAdministrador.setText("administrador");
        jrbAdministrador.setActionCommand("administrador");
        jrbAdministrador.setBounds(190, 210, 140, 23);
        jLayeredPane1.add(jrbAdministrador, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bgTipo.add(jrbUsuarioComum);
        jrbUsuarioComum.setText("Usuario Comum");
        jrbUsuarioComum.setActionCommand("Usuario Comum");
        jrbUsuarioComum.setBounds(310, 210, 150, 23);
        jLayeredPane1.add(jrbUsuarioComum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    *
    * Método que tem finalidade de limpar as propriedades da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 05/05/2011
    */
    private void limpa()
    {
        jtUsuario.setText("");     
        jpfComfirmacao.setText(""); 
        jpfSenha.setText("");
    }//private void limpa()

    /**
    *
    * Método que tem finalidade de cadastrar o usuario
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 05/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) 
    {
        String senha            = new String(jpfSenha.getPassword()); 
        String senhaconfirmada  = new String(jpfComfirmacao.getPassword()); 

        try 
        {
            if (!jtUsuario.getText().isEmpty() && !senha.isEmpty() && !senhaconfirmada.isEmpty()) {
                if (senha.equals(senhaconfirmada)) {
                    NegUsuario uc = new NegUsuario();   
                    PerUsuario u = new PerUsuario();
                    u.setLogin(Criptografia.criptografa(jtUsuario.getText()));
                    u.setSenha(Criptografia.criptografa(new String(jpfSenha.getPassword()))); 
                    u.setTipo(bgTipo.getSelection().getActionCommand());
                    uc.cadastrarUsuario(u);
                    JOptionPane.showMessageDialog(this,"Usuário cadastrado com sucesso! "); 
                    limpa();
                } else {
                    JOptionPane.showMessageDialog(
                        this,
                        "As duas senhas não são iguais! ",
                        "Erro",JOptionPane.ERROR_MESSAGE
                    );  
                }  
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "você não Preencheu todos os campos",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
                );     
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Erro! "+e.getMessage()
            );
        }//try
    }//private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt)

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JLabel jlComfirmacao;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPasswordField jpfComfirmacao;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JRadioButton jrbAdministrador;
    private javax.swing.JRadioButton jrbUsuarioComum;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}