/*
 * VisDeletarEndereco.java
 *
 * Created on 04/05/2011, 19:09:30
 */
package visao;

import javax.swing.JOptionPane;
import negocio.NegEndereco;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import persistencia.PerCondutor;
import persistencia.PerEndereco;

/**
 * Classe VisDeletarEndereco da camada de visao
 * 
 * @version 2.3 beta
 * @author Matheus Souza da Silva
 * @since 04/05/2011
 */
public class VisDeletarEndereco extends javax.swing.JInternalFrame 
{
    /**
    *
    * Método construtor da camada de Endereco
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 04/05/2011
    */
    public VisDeletarEndereco() 
    {
        initComponents();
        jlNumero.setVisible(false);
    }//public VisDeletarEndereco() 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgOpcao = new javax.swing.ButtonGroup();
        jbDeletar = new javax.swing.JButton();
        jrNumero = new javax.swing.JRadioButton();
        jlNumero = new javax.swing.JLabel();
        jlOpcao = new javax.swing.JLabel();
        jrCodigo = new javax.swing.JRadioButton();
        jtDeletar = new javax.swing.JTextField();
        jlCodigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEndereco = new javax.swing.JTable();
        jbVisualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Deletar Endereço");
        setPreferredSize(new java.awt.Dimension(1000, 670));

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbgOpcao.add(jrNumero);
        jrNumero.setText("Numero");
        jrNumero.setActionCommand("nome");
        jrNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrNumeroMouseClicked(evt);
            }
        });

        jlNumero.setText("Numero");

        jlOpcao.setText("Opção");

        jbgOpcao.add(jrCodigo);
        jrCodigo.setSelected(true);
        jrCodigo.setText("Código Endereço");
        jrCodigo.setActionCommand("codigo");
        jrCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrCodigoMouseClicked(evt);
            }
        });

        jlCodigo.setText("Código Endereço");

        jTableEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Endereço", "Endereço", "Logradouro", "Numero", "Complemento", "Bairro", "Estado", "Cidade", "Cep", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEndereco);

        jbVisualizar.setText("Visualizar");
        jbVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                    .addComponent(jtDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbVisualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jrCodigo)
                        .addGap(27, 27, 27)
                        .addComponent(jrNumero))
                    .addComponent(jlOpcao)
                    .addComponent(jlNumero)
                    .addComponent(jlCodigo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlOpcao)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrCodigo)
                    .addComponent(jrNumero))
                .addGap(29, 29, 29)
                .addComponent(jlCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNumero)
                .addGap(25, 25, 25)
                .addComponent(jtDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDeletar)
                    .addComponent(jbVisualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    *
    * Método que tem finalidade de zerar a tabela da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 04/05/2011
    */
    private void ZeraTabela()
    {
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco.getModel();
        //Zerar número de linhas da tabela
        dtm.setNumRows(0);
    }//private void ZeraTabela()
    
    /**
    *
    * Método que tem finalidade de deletar o endereco
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 04/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        try 
        {
            NegEndereco ec = new NegEndereco();
            PerEndereco e  = new PerEndereco();

            String op = jbgOpcao.getSelection().getActionCommand();

            if (op.equals("codigo")) {
                e.setIdendereco(Integer.parseInt(jtDeletar.getText()));

                /* Antes de enviar para o método
                 deletar, envia para o método
                 que verifica se realmente existe
                 o objeto no Banco */

                if (ec.buscarEnderecoCodigo(e)) {
                    ec.deletarEnderecoCodigo(e);
                } else {
                /* Se o método buscar retornar
                   false criamos uma Exceção
                   informando ao usuário que o
                   Endereço não existe */
                    throw new Exception("Endereço não Existente! ");
                }//if (ec.buscarEnderecoCodigo(e)) {

                ec.deletarEnderecoCodigo(e);
            } else {
                e.setNumero(Integer.parseInt(jtDeletar.getText()));

                /* Antes de enviar para o método
                 deletar, envia para o método
                 que verifica se realmente existe
                 o objeto no Banco */

                if (ec.buscarEnderecoNumero(e)) {
                    ec.deletarEnderecoNumero(e);
                } else {
                    throw new Exception("Endereço não Existente! ");
                }//if (ec.buscarEnderecoNumero(e)) {
            }//if (op.equals("codigo")) {

            JOptionPane.showMessageDialog(this, "Endereço Excluído com Sucesso! ");
            this.ZeraTabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Erro! "+e.getMessage()
            );
        }//try
}//GEN-LAST:event_jbDeletarActionPerformed

    /**
    *
    * Método que marcar o radio clicado
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 04/05/2011
    */
    private void jrNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrNumeroMouseClicked
        jlNumero.setVisible(true);
        jlCodigo.setVisible(false);
}//GEN-LAST:event_jrNumeroMouseClicked

    /**
    *
    * Método que marcar o radio clicado
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 04/05/2011
    */
    private void jrCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrCodigoMouseClicked
        jlNumero.setVisible(false);
        jlCodigo.setVisible(true);
}//GEN-LAST:event_jrCodigoMouseClicked

    /**
    *
    * Método que tem finalidade de carregar na inteface as informações da tabela da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 04/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void jbVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarActionPerformed
        try 
        {
            NegEndereco mc = new NegEndereco();
            PerCondutor c = new PerCondutor();
            ArrayList<PerEndereco> eAux = new ArrayList<PerEndereco>();
            eAux = mc.buscarTodosEnderecos();

            DefaultTableModel dtm=(DefaultTableModel)jTableEndereco.getModel();

                // Código para zerar o número de linhas da Tabela.
            dtm.setNumRows(0);

            String[] linha = new String[10];

            for (int i=0; i<eAux.size(); i++) {
                linha[0] = Integer.toString(eAux.get(i).getIdendereco());
                linha[1] = eAux.get(i).getEndereco();
                linha[2] = eAux.get(i).getLogradouro();
                linha[3] = Integer.toString(eAux.get(i).getNumero());
                linha[4] = eAux.get(i).getComplemento();
                linha[5] = eAux.get(i).getBairro();
                linha[6] = eAux.get(i).getEstado();
                linha[7] = eAux.get(i).getCidade();
                linha[8] = Integer.toString(eAux.get(i).getCep());
                linha[9] = eAux.get(i).getCondutor().getNome();

                dtm.addRow(linha);
            }//for (int i=0; i<eAux.size(); i++) {
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! "+e.getMessage());
        }//try
    }//GEN-LAST:event_jbVisualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEndereco;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbVisualizar;
    private javax.swing.ButtonGroup jbgOpcao;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlOpcao;
    private javax.swing.JRadioButton jrCodigo;
    private javax.swing.JRadioButton jrNumero;
    private javax.swing.JTextField jtDeletar;
    // End of variables declaration//GEN-END:variables

}
