/*
 * VisMulta.java
 *
 * Created on 02/05/2011, 21:14:44
 */
package visao;

import negocio.NegMulta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.PerMulta;

/**
 * Classe VisMulta da camada de visao
 * 
 * @version 2.3 beta
 * @author Matheus Souza da Silva
 * @since 02/05/2011
 */
public class VisMulta extends javax.swing.JInternalFrame 
{

    /**
    *
    * Método construtor do camada da visão
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 02/05/2011
    */
    public VisMulta() 
    {
        initComponents();
    }//public VisMulta() 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlInfracao = new javax.swing.JLabel();
        jlPontos = new javax.swing.JLabel();
        jlPenalidade = new javax.swing.JLabel();
        jlValor = new javax.swing.JLabel();
        jtInfracao = new javax.swing.JTextField();
        jtPontos = new javax.swing.JTextField();
        jtPenalidade = new javax.swing.JTextField();
        jtValor = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbVisualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMulta = new javax.swing.JTable();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTecnico = new javax.swing.JTable();
        jbAlterar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbLimpar1 = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlEspecialidade = new javax.swing.JLabel();
        jbSalvarAlteracoes = new javax.swing.JButton();
        jtEspecialidade = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jlCodigo = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTecnico1 = new javax.swing.JTable();
        jbAlterar1 = new javax.swing.JButton();
        jbDeletar1 = new javax.swing.JButton();
        jbLimpar2 = new javax.swing.JButton();
        jbAtualizar1 = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jlNome1 = new javax.swing.JLabel();
        jlEspecialidade1 = new javax.swing.JLabel();
        jbSalvarAlteracoes1 = new javax.swing.JButton();
        jtEspecialidade1 = new javax.swing.JTextField();
        jtNome1 = new javax.swing.JTextField();
        jlCodigo1 = new javax.swing.JLabel();
        jtCodigo1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro multa");
        setPreferredSize(new java.awt.Dimension(1000, 670));

        jlInfracao.setText("infração");

        jlPontos.setText("pontos");

        jlPenalidade.setText("penalidade");

        jlValor.setText(" valor");

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbVisualizar.setText("Visualizar");
        jbVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarActionPerformed(evt);
            }
        });

        jTableMulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Multa", "Infração", "Pontos", "Penalidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMulta);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualização"));

        jTableTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "código técnico", "nome", "especialidade"
            }
        ));
        jScrollPane2.setViewportView(jTableTecnico);

        jLayeredPane2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 30, 430, 180);

        jbAlterar.setText("Alterar");
        jLayeredPane2.add(jbAlterar);
        jbAlterar.setBounds(20, 220, 100, 23);

        jbDeletar.setText("Deletar");
        jLayeredPane2.add(jbDeletar);
        jbDeletar.setBounds(130, 220, 100, 23);

        jbLimpar1.setText("Limpar");
        jLayeredPane2.add(jbLimpar1);
        jbLimpar1.setBounds(350, 220, 100, 23);

        jbAtualizar.setText("Atualizar");
        jLayeredPane2.add(jbAtualizar);
        jbAtualizar.setBounds(240, 220, 100, 23);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Manutenção Técnico"));

        jlNome.setText("Nome");
        jLayeredPane1.add(jlNome);
        jlNome.setBounds(40, 110, 27, 14);

        jlEspecialidade.setText("Especialidade");
        jLayeredPane1.add(jlEspecialidade);
        jlEspecialidade.setBounds(40, 170, 120, 14);

        jbSalvarAlteracoes.setText("Salvar Alterações");
        jLayeredPane1.add(jbSalvarAlteracoes);
        jbSalvarAlteracoes.setBounds(20, 230, 210, 23);
        jLayeredPane1.add(jtEspecialidade);
        jtEspecialidade.setBounds(170, 160, 200, 20);
        jLayeredPane1.add(jtNome);
        jtNome.setBounds(170, 100, 200, 20);

        jlCodigo.setText("Código Técnico");
        jLayeredPane1.add(jlCodigo);
        jlCodigo.setBounds(40, 50, 72, 14);

        jtCodigo.setEditable(false);
        jLayeredPane1.add(jtCodigo);
        jtCodigo.setBounds(170, 40, 200, 20);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualização"));

        jTableTecnico1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "código técnico", "nome", "especialidade"
            }
        ));
        jScrollPane3.setViewportView(jTableTecnico1);

        jLayeredPane3.add(jScrollPane3);
        jScrollPane3.setBounds(20, 30, 430, 180);

        jbAlterar1.setText("Alterar");
        jLayeredPane3.add(jbAlterar1);
        jbAlterar1.setBounds(20, 220, 100, 23);

        jbDeletar1.setText("Deletar");
        jLayeredPane3.add(jbDeletar1);
        jbDeletar1.setBounds(130, 220, 100, 23);

        jbLimpar2.setText("Limpar");
        jLayeredPane3.add(jbLimpar2);
        jbLimpar2.setBounds(350, 220, 100, 23);

        jbAtualizar1.setText("Atualizar");
        jLayeredPane3.add(jbAtualizar1);
        jbAtualizar1.setBounds(240, 220, 100, 23);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Manutenção Técnico"));

        jlNome1.setText("Nome");
        jLayeredPane4.add(jlNome1);
        jlNome1.setBounds(40, 110, 27, 14);

        jlEspecialidade1.setText("Especialidade");
        jLayeredPane4.add(jlEspecialidade1);
        jlEspecialidade1.setBounds(40, 170, 120, 14);

        jbSalvarAlteracoes1.setText("Salvar Alterações");
        jLayeredPane4.add(jbSalvarAlteracoes1);
        jbSalvarAlteracoes1.setBounds(20, 230, 210, 23);
        jLayeredPane4.add(jtEspecialidade1);
        jtEspecialidade1.setBounds(170, 160, 200, 20);
        jLayeredPane4.add(jtNome1);
        jtNome1.setBounds(170, 100, 200, 20);

        jlCodigo1.setText("Código Técnico");
        jLayeredPane4.add(jlCodigo1);
        jlCodigo1.setBounds(40, 50, 72, 14);

        jtCodigo1.setEditable(false);
        jLayeredPane4.add(jtCodigo1);
        jtCodigo1.setBounds(170, 40, 200, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlInfracao)
                        .addGap(22, 22, 22)
                        .addComponent(jtInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jbCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jbLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbVisualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlPenalidade)
                                .addGap(4, 4, 4)
                                .addComponent(jtPenalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlPontos)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtValor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtPontos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlValor)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 491, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 492, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 491, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 492, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 491, Short.MAX_VALUE)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 492, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 491, Short.MAX_VALUE)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 492, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlInfracao)
                    .addComponent(jtInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPenalidade)
                    .addComponent(jtPenalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPontos)
                    .addComponent(jtPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCadastrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbLimpar)
                        .addComponent(jbVisualizar)))
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 321, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 321, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 321, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 321, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 321, Short.MAX_VALUE)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 321, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 321, Short.MAX_VALUE)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 321, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    /**
    *
    * Método que tem finalidade de limpar as propriedades da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 02/05/2011
    */
    public void Limpar()
    {
        jtInfracao.setText("");
        jtPontos.setText("");
        jtPenalidade.setText("");
        jtValor.setText("");
    }//public void Limpar()

    /**
    *
    * metodo que Atualiza a jTable
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 02/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void AtualizarTabela()
    {
        try 
        {
            DefaultTableModel dtm = (DefaultTableModel) jTableMulta.getModel();
            String[] linha = new String[5];

            NegMulta tc = new  NegMulta();
            ArrayList<PerMulta> tb = new ArrayList<PerMulta>();
            tb = tc.buscarTodasMultas();

            dtm.setNumRows(0); //Zerar número de linhas da tabela

            //Preenchimento da JTable
            for (int i=0; i<tb.size(); i++) {
                linha[0] = Integer.toString(tb.get(i).getIdmulta());
                linha[1] = tb.get(i).getInfracao();
                linha[2] = Integer.toString(tb.get(i).getPontos());
                linha[3] = tb.get(i).getPenalidade();
                linha[4] = Double.toString(tb.get(i).getValor());
                 
                dtm.addRow(linha);
            }//for (int i=0; i<tb.size(); i++) {

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! "+e.getMessage());
        }//try
    }//private void AtualizarTabela()

    /**
    *
    * Método que tem finalidade de cadastrar a multa
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 02/05/2011
    * @exception NumberFormatException Lança uma excessao se algum erro ocorrer
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        try 
        {
             //se qualquer um dos campos  não estiver vazio ele executa isto
            if (!jtInfracao.getText().isEmpty() && !jtPontos.getText().isEmpty() 
            && !jtPenalidade.getText().isEmpty() && !jtValor.getText().isEmpty()) {
                PerMulta m = new PerMulta();
                m.setInfracao(jtInfracao.getText());
                m.setPontos(Integer.parseInt(jtPontos.getText()));
                m.setPenalidade(jtPenalidade.getText());
                m.setValor(Double.parseDouble(jtValor.getText()));

                NegMulta mc = new NegMulta();
                mc.cadastrarMulta(m);

                JOptionPane.showMessageDialog(this, "Multa Cadastrada com Sucesso!");
                Limpar(); // chamando o metodo limpar
                AtualizarTabela(); // chamando o metodo AtualizarTabela
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Preencha Todos Os Campos!!!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
                );
             }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(
                this,
                "Dados Invalidoss!\n"+nfe.getMessage(),
                "Erro ",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                null,
                e.getMessage(),
                "Erro ",
                JOptionPane.ERROR_MESSAGE
            );
        }//try
    }//GEN-LAST:event_jbCadastrarActionPerformed

    /**
    *
    * Método que tem finalidade de limpar a tabela da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 02/05/2011
    */
    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)jTableMulta.getModel();
        dtm.setNumRows(0); //Zerar número de linhas da tabela
        Limpar(); // chamando o metodo limpar
    }//GEN-LAST:event_jbLimparActionPerformed

    /**
    *
    * Método que tem finalidade de buscar as informações do banco de dados 
    * e trazer para tabela da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 02/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void jbVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarActionPerformed
        try 
        {
            NegMulta ac = new NegMulta();
            ArrayList<PerMulta> mAux = new ArrayList<PerMulta>();
            mAux = ac.buscarTodasMultas();

            DefaultTableModel dtm=(DefaultTableModel)jTableMulta.getModel();

            // Código para zerar o número de linhas da Tabela.
            dtm.setNumRows(0);

            String[] linha = new String[5];

            for (int i=0; i<mAux.size(); i++) {
                linha[0]= Integer.toString(mAux.get(i).getIdmulta());
                linha[1]= mAux.get(i).getInfracao();
                linha[2]= Integer.toString(mAux.get(i).getPontos());
                linha[3]= mAux.get(i).getPenalidade();
                linha[4]= Double.toString(mAux.get(i).getValor());
                dtm.addRow(linha);
            }//for (int i=0; i<mAux.size(); i++) {

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! "+e.getMessage());
        }//try
    }//GEN-LAST:event_jbVisualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableMulta;
    private javax.swing.JTable jTableTecnico;
    private javax.swing.JTable jTableTecnico1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAlterar1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbAtualizar1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbDeletar1;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbLimpar1;
    private javax.swing.JButton jbLimpar2;
    private javax.swing.JButton jbSalvarAlteracoes;
    private javax.swing.JButton jbSalvarAlteracoes1;
    private javax.swing.JButton jbVisualizar;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlCodigo1;
    private javax.swing.JLabel jlEspecialidade;
    private javax.swing.JLabel jlEspecialidade1;
    private javax.swing.JLabel jlInfracao;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNome1;
    private javax.swing.JLabel jlPenalidade;
    private javax.swing.JLabel jlPontos;
    private javax.swing.JLabel jlValor;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtCodigo1;
    private javax.swing.JTextField jtEspecialidade;
    private javax.swing.JTextField jtEspecialidade1;
    private javax.swing.JTextField jtInfracao;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNome1;
    private javax.swing.JTextField jtPenalidade;
    private javax.swing.JTextField jtPontos;
    private javax.swing.JTextField jtValor;
    // End of variables declaration//GEN-END:variables

}
