/*
 * VisManutencaoMulta.java
 *
 * Created on 03/05/2011, 11:58:14
 */
package visao;

import negocio.NegMulta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.PerMulta;

/**
 * Classe VisManutencaoMulta da camada de visao
 * 
 * @version 2.3 beta
 * @author Matheus Souza da Silva
 * @since 03/05/2011
 */
public class VisManutencaoMulta extends javax.swing.JInternalFrame{

    /**
    *
    * Método construtor da camada de visão
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    */
    public VisManutencaoMulta() 
    {
        initComponents();
        this.inserirTodosMultasNaTabela();
        desabilita();  
    }//public VisManutencaoMulta() 
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jbSalvarAlteracoes = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jlValor = new javax.swing.JLabel();
        jlInfracao = new javax.swing.JLabel();
        jlPontos = new javax.swing.JLabel();
        jtPenalidade = new javax.swing.JTextField();
        jtValor = new javax.swing.JTextField();
        jtInfracao = new javax.swing.JTextField();
        jtPontos = new javax.swing.JTextField();
        jlPenalidade = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMulta = new javax.swing.JTable();
        jbAlterar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manutenção Multa");
        setPreferredSize(new java.awt.Dimension(1000, 670));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Manutenção Multa"));

        jbSalvarAlteracoes.setText("Salvar Alterações");
        jbSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarAlteracoesActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jbSalvarAlteracoes);
        jbSalvarAlteracoes.setBounds(360, 260, 210, 23);

        jlCodigo.setText("Código Multa");
        jLayeredPane1.add(jlCodigo);
        jlCodigo.setBounds(40, 50, 62, 14);

        jtCodigo.setEditable(false);
        jLayeredPane1.add(jtCodigo);
        jtCodigo.setBounds(150, 50, 800, 20);

        jlValor.setText(" valor");
        jLayeredPane1.add(jlValor);
        jlValor.setBounds(40, 230, 40, 14);

        jlInfracao.setText("infração");
        jLayeredPane1.add(jlInfracao);
        jlInfracao.setBounds(40, 100, 50, 14);

        jlPontos.setText("pontos");
        jLayeredPane1.add(jlPontos);
        jlPontos.setBounds(40, 150, 50, 14);

        jtPenalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPenalidadeActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jtPenalidade);
        jtPenalidade.setBounds(150, 190, 800, 20);
        jLayeredPane1.add(jtValor);
        jtValor.setBounds(150, 230, 800, 20);
        jLayeredPane1.add(jtInfracao);
        jtInfracao.setBounds(150, 100, 800, 20);
        jLayeredPane1.add(jtPontos);
        jtPontos.setBounds(150, 150, 800, 20);

        jlPenalidade.setText("Penalidade");
        jLayeredPane1.add(jlPenalidade);
        jlPenalidade.setBounds(40, 190, 70, 20);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualização"));

        jTableMulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Multa", "Infração", "Pontos", "Penalidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMulta);

        jLayeredPane2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 920, 190);

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbDeletar)
                    .addComponent(jbAtualizar)
                    .addComponent(jbLimpar))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.getAccessibleContext().setAccessibleName("Manutenção Multa\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    *
    * Método responsável por buscar os Multas no Banco e inseri-los na JTable
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void inserirTodosMultasNaTabela()
    {
        try 
        {
            DefaultTableModel dtm = (DefaultTableModel) jTableMulta.getModel();
            String[] linha = new String[5];

            NegMulta tc = new NegMulta();
            ArrayList<PerMulta> tb = new ArrayList<PerMulta>();
            tb = tc.buscarTodasMultas();

            //Zerar número de linhas da tabela
            dtm.setNumRows(0);

            //Preenchimento da JTable
            for (int i=0; i<tb.size(); i++) {
                linha[0] = Integer.toString(tb.get(i).getIdmulta());
                linha[1] = tb.get(i).getInfracao();
                linha[2] = Integer.toString(tb.get(i).getPontos());
                linha[3] = tb.get(i).getPenalidade();
                linha[4] = Double.toString(tb.get(i).getValor());
                dtm.addRow(linha);
            }//for (int i=0; i<tb.size(); i++) {
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! "+e.getMessage());
        }//try
    }//private void inserirTodosMultasNaTabela()

    /**
    *
    * Método que tem finalidade de limpar o Jtable
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    */
    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)jTableMulta.getModel();
        dtm.setNumRows(0); //Zerar número de linhas da tabela
    }//GEN-LAST:event_jbLimparActionPerformed

    /**
    *
    * Método que tem finalidade de limpar as propriedades da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    */
    private void limpar()
    {
        jtCodigo.setText("");
        jtInfracao.setText("");
        jtPontos.setText("");
        jtPenalidade.setText("");
        jtValor.setText("");
    }//private void limpar()
    
    /**
    *
    * Método que tem finalidade de abilitar os campos da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    */
    private void abilita()
    {
        jtInfracao.setEnabled(true);
        jtPontos.setEnabled(true);
        jtPenalidade.setEnabled(true);
        jtValor.setEnabled(true);
        jbSalvarAlteracoes.setEnabled(true);
    }//private void abilita()
    
    /**
    *
    * Método que tem finalidade de desabilitar os campos da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    */
    private void desabilita()
    {
        jtInfracao.setEnabled(false);
        jtPontos.setEnabled(false);
        jtPenalidade.setEnabled(false);
        jtValor.setEnabled(false);
        jbSalvarAlteracoes.setEnabled(false); 
    }//private void desabilita()
    
    /**
    *
    * Método que tem finalidade de deletar a multa
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        try 
        {
            if (jTableMulta.getSelectedRow() != -1) {
                /* Utiliza-se o getSelectedRow() para retornar o número
                da linha que o usuário selecionou */
                int linhaSelecionada = jTableMulta.getSelectedRow();
                
                /* O método getValueAt(linha,coluna) retorna o valor de cada coluna
                que foi selecionada. O toString converte os valores
                para String */
                String coluna1 = jTableMulta.getModel().getValueAt(linhaSelecionada, 0).toString();
                String coluna2 = jTableMulta.getModel().getValueAt(linhaSelecionada, 1).toString();
                String coluna3 = jTableMulta.getModel().getValueAt(linhaSelecionada, 2).toString();
                String coluna4 = jTableMulta.getModel().getValueAt(linhaSelecionada, 3).toString();
                String coluna5 = jTableMulta.getModel().getValueAt(linhaSelecionada, 4).toString();
                
                /* Inserindo as colunas em um objeto do tipo
                PerMulta */
                PerMulta m = new PerMulta();
                m.setIdmulta(Integer.parseInt(coluna1));
                m.setInfracao(coluna2);
                m.setPontos(Integer.parseInt(coluna3));
                m.setPenalidade(coluna4);
                m.setValor(Double.parseDouble(coluna5));

                /* Instanciando um NegMulta e enviando
                o objeto selecionado para o método:
                deletarMultaCodigo */
                NegMulta mc = new NegMulta();
                
                if (mc.deletarMultaCodigo(m) == false) {
                    /* Chamando método para atualizar os dados da JTable */
                    this.inserirTodosMultasNaTabela();

                    JOptionPane.showMessageDialog(this, mc.erros+"\nfalha ao Excluír Multa!");
                } else {
                    /* Chamando método para atualizar os dados da JTable */
                    this.inserirTodosMultasNaTabela();

                    JOptionPane.showMessageDialog(this, "Multa Excluída com Sucesso! ");
                }//if (mc.deletarMultaCodigo(m) == false) { 
                
            } else {
                throw new Exception("Você não selecionou nenhuma Multa");
            }//if (jTableMulta.getSelectedRow() != -1) {
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! "+e.getMessage());
        }//try
    }//GEN-LAST:event_jbDeletarActionPerformed

    /**
    *
    * Método que tem finalidade de alterar a multa
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        try 
        {
            if (jTableMulta.getSelectedRow() != -1) {
                int linhaSelecionada = jTableMulta.getSelectedRow();
                PerMulta m = new PerMulta();

                /* use o getSelectedRow() para retornar o valor da linha selecionada
                 depois use o getValueAt() para retornar as colunas.
                 veja como é facil.. */

                String coluna1 = jTableMulta.getModel().getValueAt(linhaSelecionada, 0).toString();
                String coluna2 = jTableMulta.getModel().getValueAt(linhaSelecionada, 1).toString();
                String coluna3 = jTableMulta.getModel().getValueAt(linhaSelecionada, 2).toString();
                String coluna4 = jTableMulta.getModel().getValueAt(linhaSelecionada, 3).toString();
                String coluna5 = jTableMulta.getModel().getValueAt(linhaSelecionada, 4).toString();
                
                jtCodigo.setText(coluna1);
                jtInfracao.setText(coluna2);
                jtPontos.setText(coluna3);
                jtPenalidade.setText(coluna4);
                jtValor.setText(coluna5);
                
                abilita(); 
                
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Você não selecionou nenhum Automovel",
                    "Erro"
                    ,JOptionPane.ERROR_MESSAGE
                );
            }//if (jTableMulta.getSelectedRow() != -1) {
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Erro! "+e.getMessage()
            );
        }//try
    }//GEN-LAST:event_jbAlterarActionPerformed

/**
*
* Método que tem finalidade de atualizar os dados da tabela da interface
* 
* @version 2.3 beta
* @author Matheus Souza da Silva
* @since 03/05/2011
* @exception Exception Lança uma excessao se algum erro ocorrer
*/    
private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
    this.inserirTodosMultasNaTabela();
}//GEN-LAST:event_jbAtualizarActionPerformed

/**
*
* Método que tem finalidade de salvar as alterações da multa
* 
* @version 2.3 beta
* @author Matheus Souza da Silva
* @since 03/05/2011
* @exception Exception Lança uma excessao se algum erro ocorrer
*/
private void jbSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarAlteracoesActionPerformed
    try
    {
        PerMulta m = new PerMulta();
        NegMulta mc = new NegMulta();

        /* Buscando os valores que o usuário alterou nos
        JTextField, montamos um objeto do tipo  PerMulta
        e enviamos para o método atualizarMultaCodigo() */
        m.setIdmulta(Integer.parseInt(jtCodigo.getText()));
        m.setInfracao(jtInfracao.getText());
        m.setPontos(Integer.parseInt(jtPontos.getText()));
        m.setPenalidade(jtPenalidade.getText());
        m.setValor(Double.parseDouble(jtValor.getText()));

        mc.atualizarMultaCodigo(m);
        limpar();

        this.inserirTodosMultasNaTabela();

        JOptionPane.showMessageDialog(
            this,
            "Multa Alterada com Sucesso!"
        );
        
        desabilita(); 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(
            this,
            "Erro! "+e.getMessage()
        );
    }//try
}//GEN-LAST:event_jbSalvarAlteracoesActionPerformed

private void jtPenalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPenalidadeActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtPenalidadeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMulta;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvarAlteracoes;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlInfracao;
    private javax.swing.JLabel jlPenalidade;
    private javax.swing.JLabel jlPontos;
    private javax.swing.JLabel jlValor;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtInfracao;
    private javax.swing.JTextField jtPenalidade;
    private javax.swing.JTextField jtPontos;
    private javax.swing.JTextField jtValor;
    // End of variables declaration//GEN-END:variables
}
