/*
 * VisManutencaoAutomovel.java
 *
 * Created on 03/05/2011, 11:58:14
 */
package visao;

import negocio.NegAutomovel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.PerAutomovel;
import persistencia.PerMulta;

/**
 * Classe VisManutencaoAutomovel da camada de visao
 * 
 * @version 2.3 beta
 * @author Matheus Souza da Silva
 * @since 03/05/2011
 */
public class VisManutencaoAutomovel extends javax.swing.JInternalFrame{

    /**
    *
    * Método construtor da camada de visão
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    */
    public VisManutencaoAutomovel() 
    {
        initComponents();
        this.inserirTodosMultasNaTabela();
        desabilita();
    }//public VisManutencaoAutomovel()

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jbSalvarAlteracoes = new javax.swing.JButton();
        jlMarca = new javax.swing.JLabel();
        jtMarca = new javax.swing.JTextField();
        jtModelo = new javax.swing.JTextField();
        jtAno = new javax.swing.JTextField();
        jtPlaca = new javax.swing.JTextField();
        jlModelo = new javax.swing.JLabel();
        jlAno = new javax.swing.JLabel();
        jlPlaca = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jlCodigo = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMulta = new javax.swing.JTable();
        jbAlterar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manutenção Automovel");
        setPreferredSize(new java.awt.Dimension(1000, 670));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Manutenção Multa"));

        jbSalvarAlteracoes.setText("Salvar Alterações");
        jbSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarAlteracoesActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jbSalvarAlteracoes);
        jbSalvarAlteracoes.setBounds(370, 240, 210, 23);

        jlMarca.setText("Marca");
        jLayeredPane1.add(jlMarca);
        jlMarca.setBounds(40, 80, 29, 14);
        jLayeredPane1.add(jtMarca);
        jtMarca.setBounds(130, 80, 810, 20);
        jLayeredPane1.add(jtModelo);
        jtModelo.setBounds(130, 120, 810, 20);
        jLayeredPane1.add(jtAno);
        jtAno.setBounds(130, 160, 810, 20);
        jLayeredPane1.add(jtPlaca);
        jtPlaca.setBounds(130, 200, 810, 20);

        jlModelo.setText("Modelo");
        jLayeredPane1.add(jlModelo);
        jlModelo.setBounds(40, 120, 34, 14);

        jlAno.setText("Ano");
        jLayeredPane1.add(jlAno);
        jlAno.setBounds(40, 160, 19, 14);

        jlPlaca.setText("Placa");
        jLayeredPane1.add(jlPlaca);
        jlPlaca.setBounds(40, 200, 25, 14);

        jtCodigo.setEditable(false);
        jLayeredPane1.add(jtCodigo);
        jtCodigo.setBounds(130, 40, 810, 20);

        jlCodigo.setText("Código Multa");
        jLayeredPane1.add(jlCodigo);
        jlCodigo.setBounds(40, 40, 62, 14);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualização"));

        jTableMulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Multa", "Marca", "Modelo", "Ano", "Placa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMulta);

        jLayeredPane2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 910, 190);

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbDeletar)
                    .addComponent(jbAtualizar)
                    .addComponent(jbLimpar))
                .addGap(19, 19, 19)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLayeredPane1.getAccessibleContext().setAccessibleName("Manutenção Multa\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    *
    * Método responsável por buscar os Multas no Banco e inseri-los na JTable
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void inserirTodosMultasNaTabela()
    {
        try 
        {
            DefaultTableModel dtm = (DefaultTableModel) jTableMulta.getModel();
            String[] linha = new String[6];

            NegAutomovel ac = new NegAutomovel();
            ArrayList<PerAutomovel> ab = new ArrayList<PerAutomovel>();
            ab = ac.buscarTodosAutomoveis();

            //Zerar número de linhas da tabela
            dtm.setNumRows(0);

            //Preenchimento da JTable
            for (int i=0; i<ab.size(); i++) {
                linha[0] = Integer.toString(ab.get(i).getIdautomovel());
                linha[1] = ab.get(i).getMarca();
                linha[2] = ab.get(i).getModelo();
                linha[3] = Integer.toString(ab.get(i).getAno());
                linha[4] = ab.get(i).getPlaca();
                linha[5] = ab.get(i).getMulta().getInfracao();
                dtm.addRow(linha);
            }//for (int i=0; i<ab.size(); i++) {

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! "+e.getMessage());
        }//try
    }//private void inserirTodosMultasNaTabela()

    /**
    *
    * Método que tem finalidade de limpar o Jtable
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    */
    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)jTableMulta.getModel();
        dtm.setNumRows(0); //Zerar número de linhas da tabela
    }//GEN-LAST:event_jbLimparActionPerformed

    /**
    *
    * Método que tem finalidade de limpar as propriedades da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    */
    private void limpar()
    {
        jtCodigo.setText("");
        jtMarca.setText("");
        jtModelo.setText("");
        jtAno.setText("");
        jtPlaca.setText("");
    }//private void limpar()
    
    /**
    *
    * Método que tem finalidade de abilitar os campos da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    */
    private void abilita()
    {
        jtMarca.setEnabled(true);
        jtModelo.setEnabled(true);
        jtAno.setEnabled(true);
        jtPlaca.setEnabled(true);
        jbSalvarAlteracoes.setEnabled(true);
    }//private void abilita()
    
    /**
    *
    * Método que tem finalidade de desabilitar os campos da interface
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    */
    private void desabilita()
    {
        jtMarca.setEnabled(false);
        jtModelo.setEnabled(false);
        jtAno.setEnabled(false);
        jtPlaca.setEnabled(false);
        jbSalvarAlteracoes.setEnabled(false); 
    }
    
    /**
    *
    * Método que tem finalidade de deletar o automovel
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        try 
        {
            if (jTableMulta.getSelectedRow() != -1) {
                /* Utilizamos o getSelectedRow() para retornar o número
                da linha que o usuário selecionou */
                int linhaSelecionada = jTableMulta.getSelectedRow();
                
                /* O método getValueAt(linha,coluna) retorna o valor de cada coluna
                que foi selecionada. O toString converte os valores
                para String */
                String coluna1 = jTableMulta.getModel().getValueAt(linhaSelecionada, 0).toString();
                String coluna2 = jTableMulta.getModel().getValueAt(linhaSelecionada, 1).toString();
                String coluna3 = jTableMulta.getModel().getValueAt(linhaSelecionada, 2).toString();
                String coluna4 = jTableMulta.getModel().getValueAt(linhaSelecionada, 3).toString();
                String coluna5 = jTableMulta.getModel().getValueAt(linhaSelecionada, 4).toString();
                
                /* Inserindo as colunas em um objeto do tipo
                PerAutomovel */
                PerAutomovel a = new PerAutomovel();
                a.setIdautomovel(Integer.parseInt(coluna1));
                a.setMarca(coluna2);
                a.setModelo(coluna3);
                a.setAno(Integer.parseInt(coluna4));
                a.setPlaca(coluna5);

                /* Instanciando um NegAutomovel e enviando
                o objeto selecionado para o método:
                deletarAutomovelCodigo */
                NegAutomovel ac = new NegAutomovel();
                
                if (ac.deletarAutomovelCodigo(a) == false) {
                    JOptionPane.showMessageDialog(this, ac.erros+"\nfalha ao Excluír Automovel!");
                    // Chamando método para atualizar os dados da JTable 
                    this.inserirTodosMultasNaTabela();
                } else {
                    // Chamando método para atualizar os dados da JTable 
                    this.inserirTodosMultasNaTabela();

                    JOptionPane.showMessageDialog(this, "Automovel Excluído com Sucesso!");
                }//if (ac.deletarAutomovelCodigo(a) == false) {

            } else {
                 JOptionPane.showMessageDialog(
                    this,
                    "Você não selecionou nenhum Automovel",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
                 );
            }//if (jTableMulta.getSelectedRow() != -1) {
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! "+e.getMessage());
        }//try
    }//GEN-LAST:event_jbDeletarActionPerformed

    /**
    *
    * Método que tem finalidade de alterar o automovel
    * 
    * @version 2.3 beta
    * @author Matheus Souza da Silva
    * @since 03/05/2011
    * @exception Exception Lança uma excessao se algum erro ocorrer
    */
    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        try 
        {
            if (jTableMulta.getSelectedRow() != -1) {
                int linhaSelecionada = jTableMulta.getSelectedRow();
                PerMulta m = new PerMulta();

                /* use o getSelectedRow() para retornar o valor da linha selecionada
                 depois use o getValueAt() para retornar as colunas.
                 veja como é facil.. */

                String coluna1 = jTableMulta.getModel().getValueAt(linhaSelecionada, 0).toString();
                String coluna2 = jTableMulta.getModel().getValueAt(linhaSelecionada, 1).toString();
                String coluna3 = jTableMulta.getModel().getValueAt(linhaSelecionada, 2).toString();
                String coluna4 = jTableMulta.getModel().getValueAt(linhaSelecionada, 3).toString();
                String coluna5 = jTableMulta.getModel().getValueAt(linhaSelecionada, 4).toString();
                
                jtCodigo.setText(coluna1);
                jtMarca.setText(coluna2);
                jtModelo.setText(coluna3);
                jtAno.setText(coluna4);
                jtPlaca.setText(coluna5);
                
                abilita();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Você não selecionou nenhum Automovel",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
                );     
            }//if (jTableMulta.getSelectedRow() != -1) {
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! "+e.getMessage());
        }//try
    }//GEN-LAST:event_jbAlterarActionPerformed

/**
*
* Método que tem finalidade de inserir as informações na tabela da interface
* 
* @version 2.3 beta
* @author Matheus Souza da Silva
* @since 03/05/2011
*/    
private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
    this.inserirTodosMultasNaTabela(); // Chamando método para atualizar os dados da JTable 
}//GEN-LAST:event_jbAtualizarActionPerformed

/**
*
* Método que tem finalidade de salvar as alterações do automovel
* 
* @version 2.3 beta
* @author Matheus Souza da Silva
* @since 03/05/2011
* @exception Exception Lança uma excessao se algum erro ocorrer
*/
private void jbSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarAlteracoesActionPerformed
    try
    {
        PerAutomovel a = new PerAutomovel();
        NegAutomovel ac = new NegAutomovel();

        /* Buscamos os valores que o usuário alterou nos
        JTextField, montamos um objeto do tipo PerAutomovel
        e enviamos para o método atualizarAutomovelCodigo() */
        a.setIdautomovel(Integer.parseInt(jtCodigo.getText()));
        a.setMarca(jtMarca.getText());
        a.setModelo(jtModelo.getText());
        a.setAno(Integer.parseInt(jtAno.getText()));
        a.setPlaca(jtPlaca.getText());

        ac.atualizarAutomovelCodigo(a);
        limpar();

        this.inserirTodosMultasNaTabela();

        JOptionPane.showMessageDialog(this, "Automovel Alterado com Sucesso! ");
        desabilita(); 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro! "+e.getMessage());
    }//try
}//GEN-LAST:event_jbSalvarAlteracoesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMulta;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvarAlteracoes;
    private javax.swing.JLabel jlAno;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlPlaca;
    private javax.swing.JTextField jtAno;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtMarca;
    private javax.swing.JTextField jtModelo;
    private javax.swing.JTextField jtPlaca;
    // End of variables declaration//GEN-END:variables
}